// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PL.Persistence.Contexts;

#nullable disable

namespace PL.Persistence.Migrations
{
    [DbContext(typeof(BaseDbContext))]
    [Migration("20220910200052_ProgrammingTechnology")]
    partial class ProgrammingTechnology
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("PL.Domain.Entities.ProgrammingLanguage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DisplayOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(10000);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("DisplayOrder");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("ProgrammingLanguages", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "C Programming Language",
                            DisplayOrder = 10000,
                            Name = "C"
                        },
                        new
                        {
                            Id = 2,
                            DisplayOrder = 10000,
                            Name = "C++"
                        },
                        new
                        {
                            Id = 3,
                            DisplayOrder = 10000,
                            Name = "Java"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Objective C from Steve Job's Next Step",
                            DisplayOrder = 10000,
                            Name = "Objective C"
                        },
                        new
                        {
                            Id = 5,
                            Description = "C Sharp Programming Language",
                            DisplayOrder = 1000,
                            Name = "C#"
                        },
                        new
                        {
                            Id = 6,
                            Description = "A programming language which was intended to work in clientside HTML.",
                            DisplayOrder = 2000,
                            Name = "JavaScript"
                        });
                });

            modelBuilder.Entity("PL.Domain.Entities.ProgrammingTechnology", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("ProgrammingLanguageId")
                        .HasColumnType("int");

                    b.Property<int>("TechnologyType")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("ProgrammingLanguageId");

                    b.HasIndex("TechnologyType");

                    b.ToTable("ProgrammingTechnologies", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Most mature JavaScript library.",
                            Name = "jQuery",
                            ProgrammingLanguageId = 6,
                            TechnologyType = 1
                        },
                        new
                        {
                            Id = 2,
                            Name = "Angular JS",
                            ProgrammingLanguageId = 6,
                            TechnologyType = 2
                        },
                        new
                        {
                            Id = 3,
                            Name = "WPF",
                            ProgrammingLanguageId = 5,
                            TechnologyType = 2
                        },
                        new
                        {
                            Id = 4,
                            Description = "Apple's native object-oriented application programming interface (API) for its desktop operating system macOS.",
                            Name = "Cocoa",
                            ProgrammingLanguageId = 4,
                            TechnologyType = 4
                        },
                        new
                        {
                            Id = 5,
                            Description = "An application framework and inversion of control container for the Java platform.",
                            Name = "Spring",
                            ProgrammingLanguageId = 3,
                            TechnologyType = 2
                        });
                });

            modelBuilder.Entity("PL.Domain.Entities.ProgrammingTechnology", b =>
                {
                    b.HasOne("PL.Domain.Entities.ProgrammingLanguage", "ProgrammingLanguage")
                        .WithMany("ProgrammingTechnologies")
                        .HasForeignKey("ProgrammingLanguageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProgrammingLanguage");
                });

            modelBuilder.Entity("PL.Domain.Entities.ProgrammingLanguage", b =>
                {
                    b.Navigation("ProgrammingTechnologies");
                });
#pragma warning restore 612, 618
        }
    }
}
