// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PL.Persistence.Contexts;

#nullable disable

namespace PL.Persistence.Migrations
{
    [DbContext(typeof(BaseDbContext))]
    partial class BaseDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("PL.Domain.Entities.ProgrammingLanguage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DisplayOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(10000);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("DisplayOrder");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("ProgrammingLanguages", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "C Programming Language",
                            DisplayOrder = 10000,
                            Name = "C"
                        },
                        new
                        {
                            Id = 2,
                            DisplayOrder = 10000,
                            Name = "C++"
                        },
                        new
                        {
                            Id = 3,
                            DisplayOrder = 10000,
                            Name = "Java"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Objective C from Steve Job's Next Step",
                            DisplayOrder = 10000,
                            Name = "Objective C"
                        },
                        new
                        {
                            Id = 5,
                            Description = "C Sharp Programming Language",
                            DisplayOrder = 1000,
                            Name = "C#"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
